services:
  php-unit:
    restart: no
    build:
      context: .
      args:
        UID: ${DUID:-1000}
        GID: ${DGID:-1000}
      dockerfile: docker/${APP_ENV}/Dockerfile
    container_name: ${APP_NAME}-php-unit
    environment:
      APP_ENV: ${APP_ENV:-local}
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app:rw
      - ./unit-config.json:/docker-entrypoint.d/config.json:ro
    networks:
      - ${APP_NAME}-network
    depends_on:
      - database

  database:
    restart: no
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: ${APP_NAME}-database
    ports:
      - 5432:5432
    volumes:
      - db-${APP_NAME}:/var/lib/postgresql/data:rw
      - ./docker/db-${APP_NAME}:/docker-entrypoint-database.d
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - ${APP_NAME}-network

volumes:
  db-sq_systems:
    driver: local

networks:
  sq_systems-network:
    driver: bridge
